image: mcr.microsoft.com/devcontainers/go:1.20
tasks:
  - name: Init
    init: go get && go mod download && go install github.com/onsi/ginkgo/v2/ginkgo
vscode:
  extensions:
    - golang.Go
    - MS-vsliveshare.vsliveshare
