name: Update Codespace Devcontainers

on:
  workflow_dispatch:
  push:
    paths:
    - '**/devcontainer.json'
    - '**/.devcontainer.json'
    - '!.devcontainer'
    branches:
    - 'main'

jobs:
  transform:
    name: Find all Bootstraps and copy their devcontainer to the rootfolder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: actions/checkout@v3
      - name: Install Dev Tools
        working-directory: .bin/
        run: npm install
      - run: |
          ./.bin/transform_and_copy_devcontainers_for_codespaces.sh
      - name: Commit new devcontainers
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'githubaction@users.noreply.github.com'
          set +e
          git add .devcontainer/ 
          git commit -m "[meta] Update codespace .devcontainers"
          git pull origin --rebase main
          set -e
          git push