name: Update README

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  transform:
    name: Generate new README and commit to repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Dev Tools
        working-directory: .bin/
        run: npm install
      - run: |
          node ./.bin/generate_README.js | tee ./README.md
      - name: Commit new README
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'githubaction@users.noreply.github.com'
          set +e
          git add README.md
          git commit -m "[meta] Update README"
          git pull origin --rebase main
          set -e
          git push
